version: '3.9'

services:
  pharmacy:
    image: marijakljestan/pharmacy:2.0
    restart: on-failure
    networks:
      - application
      - database
    environment:
      DB_CONNECTION_STRING: "host=database;port=5432;database=pharmacy;user Id=postgres;password=pharmacy;"
    depends_on:
      - database
    ports:
      - 8081:80
    volumes:
      - type: volume
        source: web-sql
        target: /app/scripts

  database:
    image: postgres:14.1
    restart: always
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: pharmacy
      POSTGRES_USER: postgres
      POSTGRES_DB: pharmacy
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: volume
        source: web-sql
        target: /docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  database-data:
    name: pharmacy-database
  web-sql:

networks:
  application:
    name: application
    driver: bridge
  database:
    name: database
    driver: bridge