version: '3.9'

services:
  gateway_hospital:
    image: anagavrilovic/hospital-gateway:latest
    networks:
      - public
      - application
    ports:
      - "8080:8080"   
    depends_on:
      - hospital
      - integration-api
      - pharmacy 

  gateway_pharmacy:
    image: anagavrilovic/pharmacy-gateway:latest
    networks:
      - public
      - application
    ports:
      - "8081:8080"
    depends_on:
      - pharmacy 

  hospital:
    image: anagavrilovic/hospital:latest
    networks:
      - application
      - database
    environment:
      DB_CONNECTION_STRING_H: "user Id=/run/secrets/POSTGRES_USER;password=/run/secrets/POSTGRES_PASSWORD_H;server=hospital-db;port=5432;database=/run/secrets/POSTGRES_DB_H;Integrated Security=true;Pooling=true;"
    depends_on:
      - hospital-db
    ports:
      - 8086:80
    volumes:
      - type: volume
        source: hospital-api-sql
        target: /app/scripts

  hospital-db:
    image: postgres:14.1
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD_H
      POSTGRES_USER: /run/secrets/POSTGRES_USER
      POSTGRES_DB: /run/secrets/POSTGRES_DB_H
    volumes:
      - type: volume
        source: hospital-database-data
        target: /var/lib/postgresql/data
      - type: volume
        source: hospital-api-sql
        target: /docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    secrets:
      - POSTGRES_PASSWORD_H
      - POSTGRES_USER
      - POSTGRES_DB_H  

  pharmacy:
    image: marijakljestan/pharmacy:latest
    networks:
      - application
      - database
    environment:
      DB_CONNECTION_STRING_P: "server=pharmacy-db;port=5432;database=/run/secrets/POSTGRES_DB_P;user Id=/run/secrets/POSTGRES_USER;password=/run/secrets/POSTGRES_PASSWORD_P;"
    depends_on:
      - pharmacy-db
    ports:
      - 8087:80
    volumes:
      - type: volume
        source: pharmacy-api-sql
        target: /app/scripts

  pharmacy-db:
    image: postgres:14.1
    networks:
      - database
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD_P
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB_P
    volumes:
      - type: volume
        source: pharmacy-database-data
        target: /var/lib/postgresql/data
      - type: volume
        source: pharmacy-api-sql
        target: /docker-entrypoint-initdb.d/
    ports:
      - 5433:5432
    secrets:
      - POSTGRES_PASSWORD_P
      - POSTGRES_USER
      - POSTGRES_DB_P  

  integration-api:
    image: marijakljestan/integration:latest
    networks:
      - application
      - database
    environment:
      DB_CONNECTION_STRING_I: "user Id=/run/secrets/POSTGRES_USER;password=/run/secrets/POSTGRES_PASSWORD_I;server=integration-db;port=5432;database=/run/secrets/POSTGRES_DB_I;Integrated Security=true;Pooling=true;"
    depends_on:
      - integration-db
    ports:
      - 8088:80
    volumes:
      - type: volume
        source: integration-api-sql
        target: /app/scripts
 
  integration-db:
    image: postgres:14.1
    networks:
      - database
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD_I
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB_I
    volumes:
      - type: volume
        source: integration-database-data
        target: /var/lib/postgresql/data
      - type: volume
        source: integration-api-sql
        target: /docker-entrypoint-initdb.d/
    ports:
      - 5434:5432
    secrets:
      - POSTGRES_PASSWORD_I
      - POSTGRES_USER
      - POSTGRES_DB_I

volumes:
  pharmacy-database-data:
    name: pharmacy-database
  hospital-database-data:
    name: hospital-database
  integration-database-data:
    name: integration-database
  pharmacy-api-sql:
  hospital-api-sql:
  integration-api-sql:

networks:
  public:
    name: public
    driver: overlay
  application:
    name: application
    driver: overlay
  database:
    name: database
    driver: overlay

secrets:
  POSTGRES_PASSWORD_H:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_DB_H: 
    external: true

  POSTGRES_PASSWORD_P:
    external: true
  POSTGRES_DB_P:
    external: true

  POSTGRES_PASSWORD_I:
    external: true
  POSTGRES_DB_I: 
    external: true
  